// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	common "niffler/internal/common"

	mock "github.com/stretchr/testify/mock"
)

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: cmd
func (_m *MockParser) Parse(cmd string) (*common.Command, error) {
	ret := _m.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *common.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*common.Command, error)); ok {
		return rf(cmd)
	}
	if rf, ok := ret.Get(0).(func(string) *common.Command); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
